version: '3.2'

services:
  web:
    build: ./web/.
    env_file: ./web/.env
    command: >
            bash -c "cd mysite
            && python manage.py migrate
            && python manage.py collectstatic --noinput
            && gunicorn mysite.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_files:/static_files
  nginx:
    build: ./nginx/.
    ports:
      - 80:80
    depends_on:
      - web
    volumes:
      - ./nginx/:/etc/nginx/conf.d
      - static_files:/static_files
